Feat style updates
valory-xyz/docs pull request #18
Opened 2023-02-06 17:24 UTC by oaksprout

This PR aims to:
- bring styling in-sync with Autonolas style guide
- simplify font usage, potentially reducing the amount we send over the wire
- add a navigation footer
- simplify design

2023-02-06 18:00 UTC, jmoreira-valory requested changes
I have compiled locally the docs, found the following issues:

1. "On this page" header has disappeared from right menu.
2. The footer (with github, twitter links, etc) does not appear (see for example how it renders here: https://squidfunk.github.io/mkdocs-material/getting-started/#with-git). This is not an issue of this PR, it was already reported to @mohandast52. 

I susggest just addressing point 1 here.

2023-02-08 11:57 UTC, oaksprout commented
1. I felt like the purpose of the right sidebar was implicit, but based on your feedback happy to re-add that heading.
2. Acknowledged that the footer isn't behaving properly, but I think having it just with these navigation buttons adds to the overall experience of the docs

2023-02-08 14:11 UTC, jmoreira-valory approved these changes

2023-02-08 14:13 UTC, jmoreira-valory commented
> 1. I felt like the purpose of the right sidebar was implicit, but based on your feedback happy to re-add that heading.

RE 1: I have seen the approach I suggested in a few doc. pages, so I assume it's usual practice.

Much nicer look with this PR.

2023-02-08 15:16 UTC, DavidMinarsch approved these changes

2023-02-08 15:16 UTC, merged